# Utiliser la dernière version d'Ubuntu comme base
FROM ubuntu:latest

# Mettre à jour APT et mettre à niveau les logiciels installés
RUN apt-get update && apt-get upgrade -y

# Commande à exécuter lorsque le conteneur est lancé
CMD echo "Hello, World!"
